package model.plague

import model.plague.TraitCategory.Symptom
import model.plague.TraitDsl.*

object Symptoms:

  final val nausea: Trait = define("Nausea", Symptom)
    .infectivity(1.0)
    .severity(1.0)
    .cost(2)
    .build()

  final val coughing: Trait = define("Coughing", Symptom)
    .infectivity(3.0)
    .severity(1.0)
    .cost(4)
    .build()

  final val rash: Trait = define("Rash", Symptom)
    .infectivity(2.0)
    .severity(1.0)
    .cost(3)
    .build()

  final val insomnia: Trait = define("Insomnia", Symptom)
    .severity(3.0)
    .cost(2)
    .cureSlowdown(0.03)
    .build()

  final val cysts: Trait = define("Cysts", Symptom)
    .infectivity(2.0)
    .severity(2.0)
    .cost(2)
    .build()

  final val anaemia: Trait = define("Anaemia", Symptom)
    .infectivity(1.0)
    .severity(1.0)
    .cost(2)
    .build()

  final val vomiting: Trait = define("Vomiting", Symptom)
    .infectivity(3.0)
    .severity(1.0)
    .cost(3)
    .prerequisite("Nausea", "Pulmonary Edema", "Diarrhea")
    .build()

  final val pneumonia: Trait = define("Pneumonia", Symptom)
    .infectivity(3.0)
    .severity(2.0)
    .cost(3)
    .prerequisite("Coughing", "Pulmonary Edema", "Pulmonary Fibrosis")
    .build()

  final val sneezing: Trait = define("Sneezing", Symptom)
    .infectivity(5.0)
    .severity(1.0)
    .cost(5)
    .prerequisite("Coughing", "Fever", "Immune Suppression")
    .build()

  final val sweating: Trait = define("Sweating", Symptom)
    .infectivity(2.0)
    .severity(1.0)
    .cost(3)
    .prerequisite("Rash", "Fever", "Skin Lesions")
    .build()

  final val paranoia: Trait = define("Paranoia", Symptom)
    .severity(4.0)
    .cost(4)
    .prerequisite("Insomnia", "Inflammation", "Seizures")
    .cureSlowdown(0.06)
    .build()

  final val hyperSensitivity: Trait = define("Hyper Sensitivity", Symptom)
    .infectivity(1.0)
    .severity(2.0)
    .cost(2)
    .prerequisite("Cysts", "Inflammation", "Paralysis")
    .build()

  final val abscesses: Trait = define("Abscesses", Symptom)
    .infectivity(4.0)
    .severity(4.0)
    .cost(2)
    .prerequisite("Cysts", "Tumors", "Systematic Infection")
    .build()

  final val hemophilia: Trait = define("Hemophilia", Symptom)
    .infectivity(4.0)
    .severity(3.0)
    .cost(3)
    .prerequisite("Anaemia", "Tumors", "Internal Hemorrhaging")
    .build()

  final val pulmonaryEdema: Trait = define("Pulmonary Edema", Symptom)
    .infectivity(5.0)
    .severity(4.0)
    .lethality(2.0)
    .cost(7)
    .prerequisite("Vomiting", "Pneumonia", "Diarrhea", "Pulmonary Fibrosis")
    .build()

  final val fever: Trait = define("Fever", Symptom)
    .infectivity(4.0)
    .severity(3.0)
    .lethality(3.0)
    .cost(9)
    .prerequisite("Sneezing", "Sweating", "Immune Suppression", "Skin Lesions")
    .build()

  final val inflammation: Trait = define("Inflammation", Symptom)
    .infectivity(2.0)
    .severity(2.0)
    .lethality(2.0)
    .cost(5)
    .prerequisite("Paranoia", "Hyper Sensitivity", "Seizures", "Paralysis")
    .build()

  final val tumors: Trait = define("Tumors", Symptom)
    .infectivity(2.0)
    .lethality(4.0)
    .cost(1)
    .prerequisite("Abscesses", "Hemophilia", "Systematic Infection", "Internal Hemorrhaging")
    .build()

  final val diarrhea: Trait = define("Diarrhea", Symptom)
    .infectivity(6.0)
    .severity(4.0)
    .lethality(1.0)
    .cost(6)
    .prerequisite("Vomiting", "Pulmonary Edema", "Dysentery")
    .build()

  final val pulmonaryFibrosis: Trait = define("Pulmonary Fibrosis", Symptom)
    .infectivity(3.0)
    .severity(3.0)
    .lethality(2.0)
    .cost(6)
    .prerequisite("Pneumonia", "Pulmonary Edema", "Total Organ Failure")
    .build()

  final val immuneSuppression: Trait = define("Immune Suppression", Symptom)
    .infectivity(2.0)
    .severity(6.0)
    .lethality(4.0)
    .cost(12)
    .prerequisite("Sneezing", "Fever", "Total Organ Failure")
    .build()

  final val skinLesions: Trait = define("Skin Lesions", Symptom)
    .infectivity(11.0)
    .severity(4.0)
    .cost(8)
    .prerequisite("Sweating", "Fever", "Necrosis")
    .build()

  final val seizures: Trait = define("Seizures", Symptom)
    .infectivity(1.0)
    .severity(7.0)
    .lethality(3.0)
    .cost(4)
    .prerequisite("Paranoia", "Inflammation", "Insanity")
    .build()

  final val paralysis: Trait = define("Paralysis", Symptom)
    .infectivity(1.0)
    .severity(5.0)
    .lethality(1.0)
    .cost(10)
    .prerequisite("Hyper Sensitivity", "Inflammation", "Coma")
    .cureSlowdown(0.1)
    .build()

  final val systematicInfection: Trait = define("Systemic Infection", Symptom)
    .infectivity(6.0)
    .severity(7.0)
    .lethality(6.0)
    .cost(17)
    .prerequisite("Abscesses", "Tumors", "Coma")
    .build()

  final val internalHemorrhaging: Trait = define("Internal Hemorrhaging", Symptom)
    .severity(9.0)
    .lethality(7.0)
    .cost(12)
    .prerequisite("Hemophilia", "Tumors", "Hemorrhagic Shock")
    .build()

  final val dysentery: Trait = define("Dysentery", Symptom)
    .infectivity(8.0)
    .severity(15.0)
    .lethality(8.0)
    .cost(19)
    .prerequisite("Diarrhea", "Insanity")
    .build()

  final val totalOrganFailure: Trait = define("Total Organ Failure", Symptom)
    .severity(20.0)
    .lethality(25.0)
    .cost(28)
    .prerequisite("Pulmonary Fibrosis", "Immune Suppression", "Coma")
    .cureSlowdown(0)
    .build()

  final val necrosis: Trait = define("Necrosis", Symptom)
    .infectivity(10.0)
    .severity(20.0)
    .lethality(13.0)
    .cost(27)
    .prerequisite("Skin Lesions", "Hemorrhagic Shock")
    .build()

  final val insanity: Trait = define("Insanity", Symptom)
    .infectivity(6.0)
    .severity(15.0)
    .cost(18)
    .prerequisite("Seizures", "Dysentery")
    .cureSlowdown(0.2)
    .build()

  final val coma: Trait = define("Coma", Symptom)
    .severity(15.0)
    .lethality(2.0)
    .cost(21)
    .prerequisite("Paralysis", "Systematic Infection", "Total Organ Failure")
    .cureSlowdown(0.24)
    .build()

  final val hemorrhagicShock: Trait = define("Hemorrhagic Shock", Symptom)
    .severity(15.0)
    .lethality(15.0)
    .cost(23)
    .prerequisite("Internal Hemorrhaging", "Necrosis")
    .build()

  /**
   * @return A set with all symptoms
   */
  def allBasics: List[Trait] = List(
    nausea, coughing, rash, insomnia, cysts, anaemia,
    vomiting, pneumonia, sneezing, sweating, paranoia, hyperSensitivity, abscesses, hemophilia,
    pulmonaryEdema, fever, inflammation, tumors,
    diarrhea, pulmonaryFibrosis, immuneSuppression, skinLesions, seizures, paralysis, systematicInfection, internalHemorrhaging,
    dysentery, totalOrganFailure, necrosis, insanity, coma, hemorrhagicShock
  )
