name: Build and Deploy ScalaDoc

on:
  push:
    branches:
      - main
      - 'feature/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Scala and sbt
        uses: olafurpg/setup-scala@v14

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

      - name: Generate ScalaDoc
        run: sbt doc

      - name: Prepare site directories
        run: |
          mkdir -p site/scaladoc
          mkdir -p site/relazione

      - name: Copy ScalaDoc
        run: cp -r target/scala-*/api/* site/scaladoc/

      - name: Copy relazione
        # Modifica il percorso qui sotto se la relazione è altrove o non presente
        run: |
          if [ -d "relazione" ]; then
            cp -r relazione/* site/relazione/
          else
            echo "Relazione directory not found, skipping copy"
          fi

      - name: Create custom index.html
        run: |
          cat > site/index.html <<EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Documentazione Progetto</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
              button {
                margin: 20px;
                padding: 15px 30px;
                font-size: 18px;
                cursor: pointer;
                border: none;
                background-color: #007bff;
                color: white;
                border-radius: 8px;
                transition: background-color 0.3s ease;
              }
              button:hover {
                background-color: #0056b3;
              }
            </style>
          </head>
          <body>
            <h1>Benvenuto nella Documentazione</h1>
            <button onclick="window.location.href='scaladoc/index.md'">ScalaDoc</button>
            <button onclick="window.location.href='relazione/index.html'">Relazione</button>
          </body>
          </html>
          EOF

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
