name: Deploy ScalaDoc to GitHub Pages

on:
  workflow_run:
    workflows: ["Generate_ScalaDoc"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-docs:
    name: Deploy to GitHub Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: scaladoc-site
          path: .

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
